### PR TITLE
Add mocked event store

### PR DESCRIPTION
**Pull request by fabiante**
This PR adds a mocked event store.

## Background

For testing I'd like to use this library without an actual mongodb and rabbitmq.

For that I need mock implementations (or in-memory) which I try to create right now.

## Changes

- Add package `eventstore/mock` including basic tests
- Update documentation (which includes texts for a mocked event bus which I'd like to add later)

### CODE REVIEW

**Comment by fabiante** [comment]
@mishudark Hi! I'd like to contribute my mock implementations for the event bus and event store.

This is currently only a draft but I want to "show" it to you anyway so that you can give me some early feedback.

Would be great to know what you think. Thanks

**Comment by mishudark** [comment]
hey, thanks for the draft, I'm close to deprecate the actual version in favor of the `v2` in that branch, that is more stable and contains better support for failures and the rewrite of badger

**Comment by mishudark** [comment]
https://github.com/mishudark/eventhus/tree/v2/v2

**Comment by fabiante** [comment]
Okay. I gues it would be more sensible then to implement the mocks not from the master branch but from v2

I'll do that some time later.

**Pull request closed without merging**
